name: Python package

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Create virtual environment
      run: python -m venv myenv
    - name: Activate virtual environment
      run: source myenv/bin/activate
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_test.txt 
    - name: Test les fonctions du fichier main_backend
      run: |
        pip install pytest pytest-cov
        pytest test_fonctions.py
